name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      #- name: Set up Python
      #  uses: actions/setup-python@v7

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v10.2.0

      - name: Build Wheel Package
        run: uv build --wheel
